// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pc_Express.Context;

#nullable disable

namespace Pc_Express.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250320151306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Pc_Express.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<string>("CategoriaNome")
                        .HasColumnType("longtext");

                    b.Property<string>("descricao")
                        .HasColumnType("longtext");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Pc_Express.Models.Pecas", b =>
                {
                    b.Property<int>("PecasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PecasID"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmEstoque")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Ispecapreferida")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("categoriaId")
                        .HasColumnType("int");

                    b.Property<string>("imagemThumbnailUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("imagemUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.HasKey("PecasID");

                    b.HasIndex("categoriaId");

                    b.ToTable("Pecas");
                });

            modelBuilder.Entity("Pc_Express.Models.Pecas", b =>
                {
                    b.HasOne("Pc_Express.Models.Categoria", "Categoria")
                        .WithMany("Peças")
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Pc_Express.Models.Categoria", b =>
                {
                    b.Navigation("Peças");
                });
#pragma warning restore 612, 618
        }
    }
}
